services:
  - type: web
    name: bekolia-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: NODE_ENV
        value: production
